--[[---------------------------------------------
-------------------------------------------------
--
-- generateWildPlantsDefs
--
-- eris
--
-------------------------------------------------
--]]---------------------------------------------

require "Foraging/forageDefinitions";

local function generateWildPlantsDefs()
	local itemDefs = {
		Violets = {
			type = "Base.Violets",
			minCount = 3,
			maxCount = 6,
			xp = 5,
			categories = { "WildPlants" },
			zones = {
				Forest      	= 10,
				DeepForest  	= 10,
				BirchForest 	= 20,
				OrganicForest	= 5,
				PHForest		= 15,
				PRForest		= 15,
				Vegitation  	= 7,
				FarmLand    	= 7,
				Farm        	= 7,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
			altWorldTexture = { {"d_plants_1_40"}, {"d_plants_1_41"}, {"d_plants_1_44"} },
			doIsoMarkerObject = true,
			itemSizeModifier = 1.0,
			isItemOverrideSize = true,
		},
		SunflowerHead = {
			type = "Base.SunflowerHead",
			minCount = 1,
			maxCount = 1,
			xp = 5,
			rainChance = -50,
			snowChance = -100,
			nightChance = -100,
			categories = { "WildPlants" },
			zones = {
				Forest      = 10,
				DeepForest  = 10,
				Vegitation  = 10,
				FarmLand    = 10,
				Farm        = 10,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = { {"d_plants_1_18", "d_plants_1_26"} },
			doIsoMarkerObject = true,
			itemSizeModifier = 1.0,
			isItemOverrideSize = true,
		},
		GrapeLeaves = {
			type = "Base.GrapeLeaves",
			minCount = 3,
			maxCount = 6,
			skill = 2,
			xp = 5,
			categories = { "WildPlants" },
			zones = {
				Forest      	= 10,
				DeepForest  	= 10,
				BirchForest  	= 15,
				Vegitation  	= 10,
				FarmLand    	= 10,
				Farm        	= 10,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
			altWorldTexture = forageSystem.worldSprites.vines,
		},
		Rosehips = {
			type = "Base.Rosehips",
			minCount = 3,
			maxCount = 6,
			skill = 4,
			xp = 5,
			rainChance = 20,
			snowChance = -100,
			categories = { "WildPlants" },
			zones = {
				Forest      	= 10,
				DeepForest  	= 10,
				BirchForest  	= 15,
				OrganicForest  	= 7,
				Vegitation  	= 15,
				FarmLand    	= 10,
				Farm        	= 10,
			},
			months = { 1, 2, 5, 6, 7, 8, 9, 10, 11, 12, },
			bonusMonths = { 9, 10, 11 },
			malusMonths = { 5, 6 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
			altWorldTexture = forageSystem.worldSprites.shrubs,
		},
		Acorn = {
			type = "Base.Acorn",
			minCount = 3,
			maxCount = 6,
			xp = 5,
			categories = { "WildPlants" },
			zones = {
				Forest      	= 10,
				DeepForest  	= 10,
				BirchForest  	= 15,
				OrganicForest  	= 15,
				PRForest  		= 15,
				PHForest  		= 15,
				Vegitation  	= 5,
				FarmLand    	= 5,
				Farm        	= 5,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
			itemSizeModifier = 1.0,
			isItemOverrideSize = true,
		},
		Dandelions = {
			type = "Base.Dandelions",
			minCount = 3,
			maxCount = 6,
			xp = 5,
			categories = { "WildPlants" },
			zones = {
				Forest      	= 10,
				DeepForest  	= 10,
				BirchForest  	= 5,
				OrganicForest  	= 5,
				PRForest  		= 10,
				PHForest  		= 10,
				Vegitation  	= 15,
				FarmLand    	= 15,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
			itemSizeModifier = 1.0,
			isItemOverrideSize = true,
		},
		Roses = {
			type = "Base.Roses",
			minCount = 1,
			maxCount = 1,
			xp = 5,
			categories = { "WildPlants" },
			zones = {
				Forest      	= 1,
				DeepForest  	= 1,
				BirchForest  	= 1,
				OrganicForest  	= 1,
				PRForest  		= 1,
				PHForest  		= 1,
				Vegitation  	= 1,
				FarmLand    	= 1,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			itemSizeModifier = 1.0,
			isItemOverrideSize = true,
		},
		Poppies = {
			type = "Base.Poppies",
			minCount = 1,
			maxCount = 4,
			xp = 5,
			categories = { "WildPlants" },
			zones = {
				Forest      	= 5,
				DeepForest  	= 5,
				BirchForest  	= 3,
				OrganicForest  	= 3,
				PRForest  		= 5,
				PHForest  		= 5,
				Vegitation  	= 7,
				FarmLand    	= 7,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
			itemSizeModifier = 1.0,
			isItemOverrideSize = true,
		},
		PoppyPods = {
			type = "Base.PoppyPods",
			minCount = 1,
			maxCount = 2,
			xp = 5,
			categories = { "WildPlants" },
			zones = {
				Forest      	= 1,
				DeepForest  	= 1,
				BirchForest  	= 1,
				OrganicForest  	= 1,
				PRForest  		= 1,
				PHForest  		= 1,
				Vegitation  	= 1,
				FarmLand    	= 1,
				Farm        	= 1,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			itemSizeModifier = 1.0,
			isItemOverrideSize = true,
		},
		Nettles = {
			type = "Base.Nettles",
			minCount = 3,
			maxCount = 6,
			xp = 5,
			categories = { "WildPlants" },
			zones = {
				Forest      	= 15,
				DeepForest  	= 15,
				Vegitation  	= 15,
				PHForest  		= 15,
				PRForest  		= 15,
				OrganicForest  	= 25,
				BirchForest  	= 25,
				FarmLand    	= 5,
				Farm        	= 5,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
			itemSizeModifier = 1.0,
			isItemOverrideSize = true,
		},
		GingerRoot = {
			type = "Base.GingerRoot",
			minCount = 1,
			maxCount = 3,
			xp = 15,
			categories = { "WildPlants" },
			zones = {
				Forest      	= 1,
				DeepForest  	= 1,
				PHForest  		= 1,
				PRForest  		= 1,
				OrganicForest  	= 1,
				BirchForest  	= 1,
				Vegitation  	= 1,
				FarmLand    	= 1,
				Farm        	= 1,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
			itemSizeModifier = 1.0,
			isItemOverrideSize = true,
		},
		Thistle = {
			type = "Base.Thistle",
			minCount = 3,
			maxCount = 6,
			xp = 5,
			categories = { "WildPlants" },
			zones = {
				Forest      	= 15,
				DeepForest  	= 15,
				Vegitation  	= 15,
				PHForest  		= 15,
				PRForest  		= 15,
				OrganicForest  	= 25,
				BirchForest  	= 25,
				FarmLand    	= 5,
				Farm        	= 5,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
			itemSizeModifier = 1.0,
			isItemOverrideSize = true,
		},
		Marigold = {
			type = "Base.Marigold",
			minCount = 3,
			maxCount = 6,
			xp = 5,
			categories = { "WildPlants" },
			zones = {
				Forest      	= 15,
				DeepForest  	= 15,
				Vegitation  	= 15,
				PHForest  		= 15,
				PRForest  		= 15,
				OrganicForest  	= 25,
				BirchForest  	= 25,
				FarmLand    	= 5,
				Farm        	= 5,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			itemSizeModifier = 1.0,
			isItemOverrideSize = true,
		},
		Dogbane = {
			type = "Base.Dogbane",
			minCount = 1,
			maxCount = 3,
			xp = 2,
			categories = { "WildPlants" },
			zones = {
				DeepForest  	= 5,
				OrganicForest  	= 5,
				BirchForest  	= 5,
				PRForest  		= 5,
				PHForest  		= 5,
				Forest      	= 10,
				Vegitation  	= 10,
				FarmLand    	= 10,
			},
			bonusMonths = { 9, 10, 11 },
			altWorldTexture = forageSystem.worldSprites.dogbane,
		},
		Tobacco = {
			type = "Base.Tobacco",
			minCount = 1,
			maxCount = 1,
			xp = 2,
			categories = { "WildPlants" },
			zones = {
				DeepForest  	= 1,
				OrganicForest  	= 1,
				BirchForest  	= 1,
				PRForest  		= 1,
				PHForest  		= 1,
				Forest      	= 1,
				Vegitation  	= 1,
				FarmLand    	= 1,
			},
			spawnFuncs = { forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = forageSystem.worldSprites.wildPlants,
		},
		WheatSheaf = {
			type = "Base.WheatSheaf",
			skill = 7,
			xp = 15,
			snowChance = -30,
			categories = { "WildPlants" },
			zones = {
				Vegitation  = 1,
				FarmLand    = 1,
				Farm        = 1,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 10 },
			malusMonths = { 11 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = forageSystem.worldSprites.wildPlants,
		},
		BarleySheaf = {
			type = "Base.BarleySheaf",
			skill = 7,
			xp = 15,
			snowChance = -30,
			categories = { "WildPlants" },
			zones = {
				Vegitation  = 1,
				FarmLand    = 1,
				Farm        = 1,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 10 },
			malusMonths = { 11 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = forageSystem.worldSprites.wildPlants,
		},
		RyeSheaf = {
			type = "Base.RyeSheaf",
			skill = 7,
			xp = 15,
			snowChance = -30,
			categories = { "WildPlants" },
			zones = {
				Vegitation  = 1,
				FarmLand    = 1,
				Farm        = 1,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 10 },
			malusMonths = { 11 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = forageSystem.worldSprites.wildPlants,
		},
		Flax = {
			type = "Base.Flax",
			skill = 7,
			xp = 15,
			snowChance = -30,
			categories = { "WildPlants" },
			zones = {
				Vegitation  = 1,
				FarmLand    = 1,
				Farm        = 1,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 10 },
			malusMonths = { 11 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = forageSystem.worldSprites.wildPlants,
		},
	};
	for itemName, itemDef in pairs(itemDefs) do
		forageDefs[itemName] = itemDef;
	end;
end

generateWildPlantsDefs();